"""add api_id and api_hash in user_bot table

Revision ID: 7cdb05c6a8a5
Revises: e2ba9dbdeebb
Create Date: 2026-04-03 19:24:27.011070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdb05c6a8a5'
down_revision: Union[str, None] = 'e2ba9dbdeebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbot', sa.Column('api_id', sa.Integer(), nullable=False))
    op.add_column('userbot', sa.Column('api_hash', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbot', 'api_hash')
    op.drop_column('userbot', 'api_id')
    # ### end Alembic commands ###
